#!/bin/bash
help_text=""
help_line="TCP Single Client, Single Server test"

echo TEST: Start a server on port 9000
echo ---------------------------------
node tcp-server -l 9000 &
sleep 2
echo

echo TEST: Start a client to connect to server
echo -----------------------------------------
node tcp-client -l -i 5 -s 10 9000
echo
sleep 2

echo TEST: Shutdown server
echo ---------------------
nc -N localhost 9000 <<< shutdown > /dev/null
